### ISSUE TITLE
provide documentation and examples

### ISSUE THREAD

**Issue by jpcaruana** [abhishek-ram/pyas2-lib#1]
Hi, 

I am looking for a AS2 lib in python. There are very few of them. It would be very nice if you provided documentation for your API and event examples (well unit test kind of document a little bit)

thanks

**Comment by abhishek-ram** [comment]
Hey,

The library is still very alpha and still have not figured out the best API structure for this library. I do not have that much time now but I hope to get to this next month.

**Comment by GudarJs** [comment]
Hi, any update?

**Comment by abhishek-ram** [comment]
I have added basic usage documentation to the readme.

**Comment by GudarJs** [comment]
Thank you, so much :grin:
