### ISSUE TITLE
Add header field "From: "

### ISSUE THREAD

**Issue by clemensbartz** [abhishek-ram/pyas2-lib#11]
This issue was originally raised in [bhishek-ram/pyas2#55](https://github.com/abhishek-ram/pyas2/issues/55):

When sending a message to the partner, the field "From: " should be added with the e-mail address visible in the organization.

Please refer to this example (A.4) from the [RFC](https://www.ietf.org/rfc/rfc4130.txt):

    AS2-Version: 1.1
    Mime-Version: 1.0
    Recipient-Address: http://10.240.1.2:8201/exchange/as2_company
    AS2-To: as2_company
    AS2-From: "AS2 Test"
    Subject: Your Requested MDN Response
    From: as2debug@example.com

For any MIME-based message, this must be added according to [RFC 2822#3.6](https://tools.ietf.org/html/rfc2822#section-3.6).

**Comment by adiroiban** [comment]
Not sure if `From` is required.

 I think that this is replaced by the `AS2-From`, which is required for any message.

I have checked the ArcESB implementation which is a certified AS2 implementation, and the `From` header is not used for sync requests.

Also, the other examples from the AS2 RFC are not using the `From` header. Only the Async example uses it.

I think that in AS2 there might be some exceptions from the email oriented RFC2822.
