### ISSUE TITLE
pyas2lib.Message.build should force binary encoding for the encrypted payload.

### ISSUE THREAD

**Issue by adiroiban** [abhishek-ram/pyas2-lib#20]
If I am sending an image (.JPG) with Django-AS2 as unsigned encrypted file pyas2lib will always transfer it as text file.. that is replace unix newline with network newline.

I am not sure where this should be fixed.

---------

I would say that pyas2lib.utils.BinaryBytesGenerator should never try to replace unix newlines.

Right now, the implementation will handle binary only if Content-Transfer-Encoding is binary and only for a certain subtype.

------

`build` method on the Message has the `content_type` argument, which can be used to force the payload but it has no way to set the  Content-Transfer-Encoding header on the payload.

----------

My suggestion is to have something line this in utils:

```python
class BinaryBytesGenerator(BytesGenerator):
    """Override the bytes generator to always produce binary data."""

    def _handle_text(self, msg):
        """
        Handle writing the binary messages to prevent default behaviour of
        newline replacements.
        """
        payload = msg.get_payload(decode=True)
        if not payload:
            return

        self._fp.write(payload)


    _writeBody = _handle_text
```

**Comment by adiroiban** [comment]
it looks like Django AS2 has no support for binary file types... so my previous suggestion is wrong.



I ended up with this fix.

Add `application/octet-stream` as an available content type for a partner in Django AS2.


Then in as2lib utils

```python
class BinaryBytesGenerator(BytesGenerator):
    """Override the bytes generator to better handle binary data."""

    def _handle_text(self, msg):
        """
        Handle writing the binary messages to prevent default behaviour of
        newline replacements.
        """
        if msg.get(
            "Content-Transfer-Encoding"
        ) == "binary" and msg.get_content_subtype() in [
            "pkcs7-mime",
            "pkcs7-signature",
            'octet-stream',
        ]:
            payload = msg.get_payload(decode=True)
            if payload is None:
                return
            else:
                self._fp.write(payload)
        else:
            super()._handle_text(msg)

    _writeBody = _handle_text
```

and in as2lib as2 Message.build I have

```
        # Read the input and convert to bytes if value is unicode/str
        # using utf-8 encoding and finally Canonicalize the payload
        self.payload = email_message.Message()
        self.payload.set_payload(data)
        self.payload.set_type(content_type)

        if content_type.lower().startswith('application/octet-stream'):
            self.payload['Content-Transfer-Encoding'] = 'binary'
        else:
            encoders.encode_7or8bit(self.payload)
```

**Comment by abhishek-ram** [comment]
Makes sense @adiroiban can you open a PR with these changes?

**Comment by adiroiban** [comment]
I will look into this. It looks like `master` branch already has BinaryBytesGenerator with support for application/octet-stream.

For my tests, I was using the released version.

I am now trying to understand the code and write automated tests. Will create a PR soon.

**Comment by adiroiban** [comment]
PR at https://github.com/abhishek-ram/pyas2-lib/pull/21 we can move the discussion there. Will open a separate PR for Django
