### ISSUE TITLE
When sending files, sign message before compression.

### ISSUE THREAD

**Issue by adiroiban** [abhishek-ram/pyas2-lib#22]
This is more about to document the current behaviour and maybe help other understand the AS2 specs.

The AS2 compression is defined at https://tools.ietf.org/html/rfc5402

The current message encapsulation in pyas2 is the one from [RFC5402 section 3.5 ](https://tools.ietf.org/html/rfc5402#section-3.5)
```
 Encrypted[ Signed [ Compressed [ File Content ]]] 

ASN1 [ MultiPart [ ASN1 [ File Content] ,  Signature] 
```

My suggestion is to use [RFC5402 section 3.6 ](https://tools.ietf.org/html/rfc5402#section-3.6)

```
Encrypted[ Compressed [ Signed [ File Content ]]]

ASN1 [ ASN1 [ MultiPart [ File Content, Signature]]]
```

A standard AS2 server will have to support both.

What I see as an advantage to 3.6 is that whether the file is compressed or not, the signature validation code will be the same.

I am -1 for adding a configuration option... but maybe that can help.

I am using pyas1 just as a testing environment for an AS2 receiver which can receive huge files over AS2 (10GB)...so for that I am using a custom ASN1 parser which can work over streamed chunks, without keeping the complete AS2 message  in memory.

**Comment by abhishek-ram** [comment]
Even if we go with 3.6 we would still need to support both 3.5 and 3.6 when parsing the incoming message, so I do not think the code would change.

**Comment by adiroiban** [comment]
Understood. Thanks!
