### ISSUE TITLE
Unit Tests Fail

### ISSUE THREAD

**Issue by dresscodeclothing** [abhishek-ram/pyas2-lib#3]
Hi Abhishek, I've been looking over this repository and noticed that a lot of the unit test fail. The first reason is the certificates in the fixtures are expired. I've put new certificates of my own, however now I get errors on all signed requests.

'PublicKeyInfo' object has no attribute 'keys'

Let me know if I'm doing something wrong with my new certificates?

**Comment by abhishek-ram** [comment]
Are you using the master branch, I just ran the tests and they passed...

**Comment by dresscodeclothing** [comment]
Hi Abhishek, I messed up, I forgot to call install and build on the setup.py.
