### ISSUE TITLE
release 1.4.3

### ISSUE THREAD

**Issue by JocelynDelalande** [abhishek-ram/pyas2-lib#59]
Please release a ~~1.4.2~~ 1.4.3 including #57 

Current build is unusable as-is.

Thanks :).

**Comment by abhishek-ram** [comment]
I have release 1.4.2, not sure why its not showing up

**Comment by JocelynDelalande** [comment]
I meant 1.4.3, as 1.4.2 does not include the fix.

**Comment by abhishek-ram** [comment]
Done, https://github.com/abhishek-ram/pyas2-lib/releases/tag/v1.4.3

**Comment by JocelynDelalande** [comment]
Wow, quick, thanks :-)
